const nome = prompt("Nome")
let dataNasc = Number(prompt("Data de nascimento"))
let end = prompt("Endereço")
const cpf = Number(prompt("CPF"))
let escolaridade = prompt("Escolaridade")
let cnh = prompt("Possui CNH?")
let numFilhos = Number(prompt("Quantos filhos possui?"))
let cargo = prompt("Cargo atual?")
let salario = Number(prompt("Salario"))
let comissao = prompt("Recebe comissão? Se sim, informe a porcentagem, caso não, responda com zero")
const admissao = Number(prompt("Informe o ano de admissão"))

console.log(nome, typeof nome)
console.log(dataNasc, typeof dataNasc)
console.log(end, typeof end)
console.log(cpf, typeof cpf)
console.log(escolaridade, typeof escolaridade)
console.log(cnh, typeof cnh)
console.log(numFilhos, typeof numFilhos)
console.log(cargo, typeof cargo)
console.log(salario, typeof salario)
console.log(comissao, typeof comissao)
console.log(admissao, typeof admissao)


